"use client"

import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SessionWrapper from "@/components/SessionWrapper";
import Header from "@/components/Header";
import { usePathname } from "next/navigation";


// export const metadata: Metadata = {
//   title: "Repo chat",
//   description: "Generated by create next app",
// };

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hiddenLogoPaths = ['/sign-in'].includes(pathname);
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={cn("min-h-screen bg-zinc-950 font-sans antialiased",fontSans.variable)}>
          {hiddenLogoPaths ? (
            <Header logoPresent={false}/>
          ) : (
            <Header logoPresent = {true} />
          )}
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
